### PR TITLE
Fix for the #125 and #126

### PR DESCRIPTION
**Pull request by VoOoLoX**
Tested on Arch Linux only

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
Standard seems to fail for some missing spaces. Can you please run `standard --fix` and push that to your PR?

**Comment by VoOoLoX** [comment]
`src\main\tray.js:5:3: 'session' is assigned a value but never used.` Should I remove `session` or should I leave it, since it seems like standard won't fix it for me?

**Comment by bil-elmoussaoui** [comment]
You can remove it :+1:

**Comment by terkelg** [comment]
Thanks folks

**Pull request merged**
