### PR TITLE
Implemented multi-account switching

### PR DESCRIPTION
**Pull request by anatolinicolae**
Adding feature #49, I told you it was coming! 🎉

@terkelg Actually works with two accounts, easy to allow others anyway (clean and commented btw), but after a cleanup I'll be porting this further by allowing more than 2 accounts.

Enjoy! 🍻

### CODE REVIEW

**Comment by terkelg** [comment]
Awesome @anatolinicolae  🎉 This is a really great addition to Ramme!

**Comment by man2** [comment]
awesome! why is it still not merged?

**Comment by anatolinicolae** [comment]
It is not merged yet because we're doing a project rewrite, merging the mess would be pointless so we'll just include the feature in v3. 😉

**Comment by anatolinicolae** [comment]
Coming on branch v3.

**Comment by EnricoMonese** [comment]
Any news on this? 👍

**Pull request closed without merging**
