### PR TITLE
Add preload window and window manager

### PR DESCRIPTION
**Pull request by octacian**
ramme preload both

This PR adds a preload window which is shown while the main window is loading the main Instagram website, and closed once the main window is shown (i.e. when the DOM is ready). The loading bar visible in the screenshot is animated not unlike the bar that is shown at the top of the Instagram website when switching between pages.

In order to achieve this functionality, I've entirely replaced the old window creation functions with a sort of window manager library, that allows registering windows to be opened or closed at a later time - these windows can even be managed to some extent via IPC. To get an idea of what the window manager does, take a look at the end of the `app/src/main/window.js` file.

This PR also *seems* to fix an issue I've noticed that seems to cause the window to quit during the "singleton" at times when it should not.

### Testing

When testing this PR, I'd suggest that you comment out line 17-19 (shows debug tools), as the preload window is not resizable causing developer tools to make it hard to view. If you'd like to prevent the preload window from closing so fast, comment out line 157. In order to make the window resizable, comment out line 46 and line 49.

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
The AppVeyor build fails due to some standard issues. Can you either fix them or just run `standard` which will take care of that 
Thanks

**Comment by octacian** [comment]
CI issues fixed.

I wonder if it would be better to combine this all into one commit? I'll leave it as is for now though.

**Comment by terkelg** [comment]
Thanks for the PR. Have you tried this @bil-elmoussaoui?

**Comment by bil-elmoussaoui** [comment]
@terkelg Not yet, i will try to do that as soon as possible

**Comment by octacian** [comment]
**Update:**

* Preload window now reacts to dark mode by enforcing the background color change and by changing the color of the `Loading...` text (screenshot can be found in the OP)
* `.`s of the `Loading...` are now animated, changing in number every 0.5 seconds
* Loading bar animation timing has been changed from `ease` to `linear` (visually nicer)

There *shouldn't* be any build issues unless I'm supposed to use single quotes in HTML as well. Come to think of it, I probably am, but I'll wait for someone to tell me for sure.

**Comment by terkelg** [comment]
Awesome. Looks like appveyor is faling though. Looking forward to marge this into the project

**Comment by octacian** [comment]
Fixed the AppVeyor build. TravisCI *should* be fine already.

**Comment by terkelg** [comment]
Thanks!

**Pull request merged**
