### PR TITLE
Windows installer

### PR DESCRIPTION
**Pull request by VoOoLoX**

### CODE REVIEW

**Comment by terkelg** [comment]
I'm not able to check this out at the moment. Can you explain a bit more what this does?

**Comment by VoOoLoX** [comment]
It downloads release zip file, extracts it and makes shortcut on desktop

Here is the gif of it in action: http://vo0olox.ga/gifs/2016-09-18_18-23-29.gif  (It huge,and it takes some time to load)

**Comment by terkelg** [comment]
Looks cool, and fun idea! However, I'm not sure it should be in the main repo, maybe It can have a repo of it's own?

**Comment by VoOoLoX** [comment]
Sure, but it would be nice if you can just add a file with up to date release version in it so installer knows which version to download (Like this https://github.com/VoOoLoX/ramme/blob/master/releases)

**Comment by terkelg** [comment]
Awesome! You can get the latest release from this API endpoint: ```https://api.github.com/repos/terkelg/ramme/releases```. 

Can you make a new pull request to the README? It could cool to link to your installer repo under the Windows download section.

**Pull request closed without merging**
