### PR TITLE
hide "Open in app" button

### PR DESCRIPTION
**Pull request by gingerbeardman**

### CODE REVIEW

**Comment by terkelg** [comment]
Nice!
Can I get you to place the code right below the other "hide app banner" code on line 40? That could be awesome.

**Comment by gingerbeardman** [comment]
done!

**Comment by gingerbeardman** [comment]
I redid the selector to match the one above, it is very similar: `._28zbs._nl1vc`

**Comment by zeke** [comment]
What do those class names mean?

**Comment by gingerbeardman** [comment]
@zeke they are generated by React so the meanings, if any, are obfuscated.

**Comment by terkelg** [comment]
Great work, thanks for the little refactor.
@zeke as @gingerbeardman said, it's classes generated by the React framework.

**Pull request merged**
