### PR TITLE
Hackish fixes for #82 #104 #101 #100 #109 #102

### PR DESCRIPTION
**Pull request by VoOoLoX**
Use of base64 encoded images to avoid errors and few css tweaks

### CODE REVIEW

**Comment by terkelg** [comment]
Awesome @VoOoLoX!

**Comment by terkelg** [comment]
Maybe I was too quick to merge this one. I don't think it's a good idea to hide the title bar. You lose the discover button and the setting button in the profile view. What do you think?
@anatolinicolae @VoOoLoX

**Comment by VoOoLoX** [comment]
@terkelg Ooops I didn't notice.I'll look into it in a few hours.
Sorry for that.

**Comment by terkelg** [comment]
No problem :)

**Pull request merged**
