### PR TITLE
Add system toolbar

### PR DESCRIPTION
**Pull request by neighborhood999**
Toolbar have：
- Show / Hide ramme
- GitHub (official repo)
- Issue (for any have question user or developer)
- Quit ramme

### CODE REVIEW

**Comment by vintagesucks** [comment]
The tray icon looks messy on Windows. From the [docs](https://github.com/electron/electron/blob/master/docs/api/tray.md):
> On Windows it is recommended to use ICO icons to get best visual effects.

We should find a compromise between #20 and #21.

**Comment by neighborhood999** [comment]
@vintagesucks Sorry, I missed your PR.
I have Linux and Windows machine, maybe you can let me finish this job :-).

**Comment by neighborhood999** [comment]
Done.

**Comment by vintagesucks** [comment]
@neighborhood999 Looking good, I'll close my PR.

Could you add the click-tray-icon-to-open functionality I added in #20, though? I think it's pretty handy.

```
tray.on('click', function handleClicked () {
  mainWindow.show();
});
```

**Comment by neighborhood999** [comment]
@vintagesucks Yep！That's a cool feature, add it. I already test on Windows it work perfect.

**Comment by terkelg** [comment]
Awesome work @neighborhood999 and @vintagesucks. Thanks for helping out with Ramme.
I like it, and it's a great addition to the app. Is it possible that you can refactor the tray logic intro a separate file like I've done with menu.js and as Sindre does here https://github.com/sindresorhus/caprine/? High five!

**Comment by vintagesucks** [comment]
@terkelg Done, see PR #23

**Comment by neighborhood999** [comment]
Hey @vintagesucks, thanks your work, but I think you don't need open new PR for this ;-).

**Pull request merged**
