### PR TITLE
Pull to refresh #10 #63

### PR DESCRIPTION
**Pull request by VoOoLoX**
Not the best implementation, but it works i guess?
Scroll up 3 times in a row to refresh the page (Edit: Forgot to mention, you have to be on top of the page and then scroll 3 times in a row)

### CODE REVIEW

**Comment by mckennajones** [comment]
Seems like a reasonable solution to me for a desktop app. It's not a feature you often see on desktop apps.

**Comment by terkelg** [comment]
Nice! What about some visual feedback? If you check if the user is ```0``` from the top, and scroll ```x``` up then add class to animate hidden element, like https://github.com/apeatling/web-pull-to-refresh

**Comment by VoOoLoX** [comment]
http://i.imgur.com/Lr7OZMj.gif

When you scroll up 2 times it shows it and if you scroll one more time it reloads the page

**Comment by terkelg** [comment]
Nice – I'll merge this for the next release

**Comment by terkelg** [comment]
I'm closing this for now sorry. Too much in the codebase have changed since

**Pull request closed without merging**
