### PR TITLE
Solved issue #203 (back button)

### PR DESCRIPTION
**Pull request by Duxy1996**
One way to solve the problem and inject a button to go back in the interfece.

Here is a example how it looks and how it works:

ramme_explanation

### CODE REVIEW

**Comment by anatolinicolae** [comment]
Lint your code fam (`standard --fix`) and push new commits. Will merge on success checks.

**Comment by anatolinicolae** [comment]
Will also point you to [`renderer/js/index.js`](https://github.com/terkelg/ramme/blob/master/app/src/renderer/js/index.js) which is run in the webview therefore no need to inject other JS.

**Comment by anatolinicolae** [comment]
Updates?

**Comment by Duxy1996** [comment]
This night I will check it, sorry I did not see de coment.

**Comment by Duxy1996** [comment]
I have done the npm test and anything faild. Sorry 4 being late.

**Pull request merged**
